### ISSUE TITLE
Yumex crash : Gdmsession error

### ISSUE THREAD

**Issue by eddy02** [timlau/yumex-dnf#12]
Traceback (most recent call last):
  File "/bin/yumex-dnf", line 30, in <module>
    from yumex import YumexApplication
  File "/usr/lib/python3.4/site-packages/yumex/__init__.py", line 24, in <module>
    from yumex.misc import doGtkEvents, _, CONFIG, ExceptionHandler
  File "/usr/lib/python3.4/site-packages/yumex/misc.py", line 165, in <module>
    class YumexConf(config.BaseConfig):
  File "/usr/lib/python3.4/site-packages/yumex/misc.py", line 188, in YumexConf
    hb_default = os.environ['GDMSESSION'] in ['gnome-shell']
  File "/usr/lib64/python3.4/os.py", line 633, in __getitem__
    raise KeyError(key) from None
KeyError: 'GDMSESSION'

**Comment by timlau** [comment]
@eddy02 what desktop are you running ?

**Comment by eddy02** [comment]
Thanks  it's working now (rawhide plasma5).
