### ISSUE TITLE
Cant open local rpm having space in its path!

### ISSUE THREAD

**Issue by moceap** [timlau/yumex-dnf#146]
![2016-12-24 10-08-54](https://cloud.githubusercontent.com/assets/4345211/21465788/4dde8c96-c9c2-11e6-828a-e9c54fc7c4b7.png)

**Comment by genodeftest** [comment]
This is the traceback:
```
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/__init__.py", line 83, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 404, in Install
    value = self.install(cmds)
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/__init__.py", line 412, in install
    po = self.base.add_remote_rpm(cmd)
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 925, in add_remote_rpm
    return self.sack.add_cmdline_package(path)
OSError: Can not load RPM file: b/usbguard-0.6.3-0.1.1483094295.fc25.src.rpm.
 (36)
```

**Comment by timlau** [comment]
created a PR for dnfdaemon

https://github.com/manatools/dnfdaemon/pull/52
