### ISSUE TITLE
Yumex-DNF throws an error whenever I try to install a package group.

### ISSUE THREAD

**Issue by audreytoskin** [timlau/yumex-dnf#159]
I was originally trying to install the KDE package groups when I got this error.

```
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.6/site-packages/dnfdaemon/server/__init__.py", line 83, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 372, in GroupInstall
    value = self.group_install(cmds)
  File "/usr/lib/python3.6/site-packages/dnfdaemon/server/__init__.py", line 391, in group_install
    self.base.group_install(grp, pkg_types)
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 1519, in group_install
    strict)
  File "/usr/lib/python3.6/site-packages/dnf/comps.py", line 90, in install_or_skip
    return install_fnc(grp_or_env_id, types, exclude, strict)
  File "/usr/lib/python3.6/site-packages/dnf/comps.py", line 600, in _group_install
    raise ValueError(_("Group_id '%s' does not exist.") % ucd(group_id))
ValueError: Group_id '<dnf.comps.Group object at 0x7fb584960a90>' does not exist.
 (36)
```

I got the same thing though when trying to install other package groups, even ones I already had installed, except the final line changed...

```
ValueError: Group_id '<dnf.comps.Group object at 0x7f28c8057940>' does not exist.
 (36)
```

**Comment by audreytoskin** [comment]
* Fedora 26 Workstation x86_64
* yumex-dnf-4.3.3-4.1.fc26
* dnf 2.6.3

**Comment by timlau** [comment]
This is caused by some changes in DNF API and dnfdaemon is not updated yet.
I have made et fix to dnfdaemon to make group install work again.
https://github.com/manatools/dnfdaemon/pull/51
currently group install/remove is disabled in yumex-dnf, but will be re enabled when the issue is fixed.

**Comment by timlau** [comment]
fixed, need upstream dnfdaemon to work
https://github.com/timlau/yumex-dnf/commit/07dfebd740290358fcb6c2036dda19a89a6e28b2
