### ISSUE TITLE
dnf.exceptions.MarkingError: No match for argument: <some-package>

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#161]
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.MarkingError: Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.9/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 485, in AddTransaction
    value = self.add_transaction(pkg_id, action)
  File "/usr/lib/python3.9/site-packages/dnfdaemon/server/__init__.py", line 552, in add_transaction
    rc = self.base.package_upgrade(po)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 2074, in package_upgrade
    raise dnf.exceptions.MarkingError(
dnf.exceptions.MarkingError: No match for argument: Packages/f/fedora-packager-kerberos-0.6.0.6-2.fc34.noarch.rpm: fedora-packager-kerberos
 (36)

**Comment by timlau** [comment]
![yumex](https://user-images.githubusercontent.com/283985/121843488-9b976e80-cce2-11eb-88f4-6bfbeabc3981.PNG)

Looks like the problem occurs when the we try to add a package to transaction there is all ready added to the transaction, pulled in as a requirement for a previous added package

**Comment by timlau** [comment]
Output from dnf 
```
================================================================================
 Package                      Arch       Version              Repository   Size
================================================================================
Upgrading:
 fedora-packager              noarch     0.6.0.6-2.fc34       updates      27 k
 fedora-packager-yubikey      noarch     0.6.0.6-2.fc34       updates      21 k
Installing weak dependencies:
 fedora-packager-kerberos     noarch     0.6.0.6-2.fc34       updates      24 k

Transaction Summary
================================================================================
Install  1 Package
Upgrade  2 Packages
```

**Comment by timlau** [comment]
Look like it is a weak dependency there is installed, not and update
so the problem can be that dnfdaemon return weak dependencies as updates, It should not do that

**Comment by timlau** [comment]
```
sudo dnf list updates
Last metadata expiration check: 0:26:57 ago on Mon 14 Jun 2021 07:15:24 AM CEST.
Available Upgrades
fedora-packager.noarch                                         0.6.0.6-2.fc34                                 updates
fedora-packager-yubikey.noarch                                 0.6.0.6-2.fc34                                 updates
```

**Comment by timlau** [comment]
created a PR to dnfdaemon to fix the issue
https://github.com/manatools/dnfdaemon/pull/49
