### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Python.AttributeError when selecting repositories in preferences

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#166]
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.9/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 223, in GetRepo
    value = self.get_repo(repo_id)
  File "/usr/lib/python3.9/site-packages/dnfdaemon/server/__init__.py", line 351, in get_repo
    repo_conf = dict([(c, getattr(repo, c) if 'VectorString' not in str(type(getattr(repo, c))) else list(getattr(repo, c))) for c in optionKeys])
  File "/usr/lib/python3.9/site-packages/dnfdaemon/server/__init__.py", line 351, in <listcomp>
    repo_conf = dict([(c, getattr(repo, c) if 'VectorString' not in str(type(getattr(repo, c))) else list(getattr(repo, c))) for c in optionKeys])
  File "/usr/lib/python3.9/site-packages/dnf/conf/config.py", line 67, in __getattr__
    option = getattr(self._config, name)
AttributeError: 'ConfigRepo' object has no attribute 'failovermethod'
 (36)

**Comment by timlau** [comment]
```
~ $ sudo dnf list installed dnf dnfdaemon yumex-dnf
Installed Packages
dnf.noarch              4.9.0-1.fc34                       @updates                                        
dnfdaemon.noarch        0.3.21-0.1.git20210702.fc34        @copr:copr.fedorainfracloud.org:timlau:yumex-dnf
yumex-dnf.noarch        4.4.1-0.1.git20210928.fc34         @copr:copr.fedorainfracloud.org:timlau:yumex-dnf

```
