### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.MarkingError

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-dnf#167]
g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.MarkingError: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.10/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 488, in AddTransaction
    value = self.add_transaction(pkg_id, action)
  File "/usr/lib/python3.10/site-packages/dnfdaemon/server/__init__.py", line 579, in add_transaction
    rc = self.base.package_upgrade(po)
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 2075, in package_upgrade
    raise dnf.exceptions.MarkingError(
dnf.exceptions.MarkingError: No match for argument: Packages/g/gtk4-devel-docs-4.4.1-1.fc35.noarch.rpm: gtk4-devel-docs
 (36)

**Comment by timlau** [comment]
Investigate the cause of this erros
We need som better handling of these kind of errors

**Comment by timlau** [comment]
![image](https://user-images.githubusercontent.com/283985/140497671-05dfb4a4-80df-47cc-9c52-bc2e6fab9684.png)

**Comment by timlau** [comment]
![image](https://user-images.githubusercontent.com/283985/140497824-e9bfad08-a506-44fc-b634-4bd3a3d0a8c5.png)

**Comment by timlau** [comment]
```
11:37:02: populate took 0.00 sec
11:37:09: adding: update gtk4,0,4.4.1,1.fc35,x86_64,updates
11:37:09: adding: update gtk4-devel,0,4.4.1,1.fc35,x86_64,updates
11:37:09: adding: update gtk4-devel-docs,0,4.4.1,1.fc35,noarch,updates
11:37:09: EXCEPTION : g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.MarkingError: Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.10/site-packages/dnfdaemon/server/__init__.py", line 68, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 488, in AddTransaction
    value = self.add_transaction(pkg_id, action)
  File "/usr/lib/python3.10/site-packages/dnfdaemon/server/__init__.py", line 579, in add_transaction
    rc = self.base.package_upgrade(po)
  File "/usr/lib/python3.10/site-packages/dnf/base.py", line 2075, in package_upgrade
    raise dnf.exceptions.MarkingError(
dnf.exceptions.MarkingError: No match for argument: Packages/g/gtk4-devel-docs-4.4.1-1.fc35.noarch.rpm: gtk4-devel-docs
 (36) 
11:37:09: err:  [] - msg: 
11:37:17: Unlock the DNF root daemon
11:37:17: Exit the DNF root daemon

(yumex-dnf:25472): Gtk-CRITICAL **: 11:37:17.043: gtk_main_quit: assertion 'main_loops != NULL' failed

```

**Comment by timlau** [comment]
Selecting only gtk4 for update works, but selecting all make it fail
gtk4-devel-docs is the one that causes problems
![image](https://user-images.githubusercontent.com/283985/140498234-8912bb97-2f59-48cd-afcf-a24fb44f636d.png)

**Comment by timlau** [comment]
daemon log:
```
11:45:41: GetPackages started args: (dbus.String('updates'), dbus.Array([dbus.String('summary'), dbus.String('size')], signature=dbus.Signature('s'))) 
11:45:41:  --> Upgrade : gtk4-4.4.1-1.fc35.x86_64 action: 6 reason: 0
11:45:41:  --> Upgraded : gtk4-4.4.0-4.fc35.x86_64 action: 7 reason: 0
11:45:41:  --> Upgrade : gtk4-devel-4.4.1-1.fc35.x86_64 action: 6 reason: 0
11:45:41:  --> Upgraded : gtk4-devel-4.4.0-4.fc35.x86_64 action: 7 reason: 0
11:45:41:  --> Upgrade : gtk4-devel-docs-4.4.1-1.fc35.noarch action: 6 reason: 0
11:45:41:  --> Upgraded : gtk4-devel-docs-4.4.0-4.fc35.x86_64 action: 7 reason: 2
11:45:41:  --> Upgrade : gtk4-devel-tools-4.4.1-1.fc35.x86_64 action: 6 reason: 2
11:45:41:  --> Upgraded : gtk4-devel-tools-4.4.0-4.fc35.x86_64 action: 7 reason: 2
11:45:41: GetPackages ended
11:45:41: GetPackages started args: (dbus.String('obsoletes'), dbus.Array([dbus.String('summary'), dbus.String('size')], signature=dbus.Signature('s'))) 
11:45:41: GetPackages ended
11:45:44: GetAttribute started args: (dbus.String('gtk4-devel-docs,0,4.4.1,1.fc35,noarch,updates'), dbus.String('pkgtags')) 
11:45:44: GetAttribute ended
11:45:44: GetAttribute started args: (dbus.String('gtk4-devel-docs,0,4.4.1,1.fc35,noarch,updates'), dbus.String('description')) 
11:45:44: GetAttribute ended
11:45:44: GetAttribute started args: (dbus.String('gtk4-devel-docs,0,4.4.1,1.fc35,noarch,updates'), dbus.String('url')) 
11:45:44: GetAttribute ended
11:45:46: ClearTransaction started args: () 
11:45:46: ClearTransaction ended
11:45:46: AddTransaction started args: (dbus.String('gtk4-devel-docs,0,4.4.1,1.fc35,noarch,updates'), dbus.String('update')) 
Package gtk4-devel-docs not installed, cannot update it.
11:45:48: Unlock started args: () 
11:45:48: UNLOCK: Lock Release by :1.201
11:45:48: Unlock ended
11:45:48: Exit started args: () 
11:45:48: Exit ended
```

**Comment by timlau** [comment]
Looks like the gtk4-devel-docs package changes arch from x86_64 to noarch
**11:45:41: --> Upgrade : gtk4-devel-docs-4.4.1-1.fc35.noarch action: 6 reason: 0
11:45:41: --> Upgraded : gtk4-devel-docs-4.4.0-4.fc35.x86_64 action: 7 reason: 2**

**Comment by timlau** [comment]
```
sudo dnf update gtk4-devel-docs-4.4.1-1.fc35.noarch
Last metadata expiration check: 0:34:23 ago on Fri 05 Nov 2021 11:25:57 AM CET.
Package gtk4-devel-docs.noarch available, but installed for different architecture.
Dependencies resolved.
=================================================================================================================
 Package                         Architecture          Version                      Repository              Size
=================================================================================================================
Upgrading:
 gtk4                            x86_64                4.4.1-1.fc35                 updates                4.4 M
 gtk4-devel                      x86_64                4.4.1-1.fc35                 updates                5.6 M
 gtk4-devel-docs                 noarch                4.4.1-1.fc35                 updates                7.2 M
 gtk4-devel-tools                x86_64                4.4.1-1.fc35                 updates                 11 M

Transaction Summary
=================================================================================================================
Upgrade  4 Packages

```

**Comment by timlau** [comment]
looks like the `dnf.Base.package_upgrade` can't handle a update with another arch, but `dnf.Base.upgrade` can
so we don't see that issue when running the dnf on commandline.

**Comment by oranmehavi** [comment]
Are there any developments regarding this issue?

**Comment by timlau** [comment]
No, no new progress, It is an problem with dnf api, It can no be fixed in yumex, need to fix it in dnfdaemon or in core dnf.
It is a corner case there is triggering this and is easy to workaround by selecting the main package only, so it has a very low priority to fix it.
