### ISSUE TITLE
Crash when selecting package

### ISSUE THREAD

**Issue by JohanAR** [timlau/yumex-dnf#170]
Sorry for the bad problem report, I don't know exactly what package that triggered the crash, but hopefully the backtrace will tell you something at least:

```
packageinfo.py:149:add_url:TypeError: Argument 1 does not allow None as a value

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yumex/gui/window/__init__.py", line 838, in on_pkg_view_selection_changed
    self.info.set_package(pkg)
  File "/usr/lib/python3.10/site-packages/yumex/gui/widgets/packageinfo.py", line 189, in set_package
    self.update()
  File "/usr/lib/python3.10/site-packages/yumex/gui/widgets/packageinfo.py", line 199, in update
    self._show_description()
  File "/usr/lib/python3.10/site-packages/yumex/gui/widgets/packageinfo.py", line 246, in _show_description
    self.add_url(url_hp, url_hp, newline=True)
  File "/usr/lib/python3.10/site-packages/yumex/gui/widgets/packageinfo.py", line 149, in add_url
    tag = self._tags.lookup(text)
TypeError: Argument 1 does not allow None as a value
```

Maybe it's as easy as adding a None check to some function

**Comment by timlau** [comment]
What version of yumex are you running ?

`sudo dnf list yumex-dnf`

**Comment by JohanAR** [comment]
Sorry, I gave up on reinstalled my OS and I don't have that VM any more. It was the version Nobara Project was using 2 weeks ago :)

We can close this issue if that makes it impossible to troubleshoot it, just thought I'd mention it in case you wanted to add some safety checks to the code.
