### ISSUE TITLE
[4.1.6] Tracebacks: AttributeError: '_ResultTuple' object has no attribute 'get_tags'

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#94]
As noted in #93 by @raveit65, yumex-dnf 4.1.6 prints some errors when running:

```
$ yumex-dnf 
/usr/lib/python3.5/site-packages/yumex/__init__.py:69: Warning: invalid cast from 'GtkBox' to 'GtkWindow'
  self.ui.add_from_file(const.DATA_DIR + '/yumex.ui')

(yumex-dnf:15160): Gtk-CRITICAL **: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
/usr/lib/python3.5/site-packages/dnfdaemon/client/__init__.py:291: PyGIDeprecationWarning: GObject.G_MAXINT is deprecated; use GLib.MAXINT instead
  user_data=data, timeout=GObject.G_MAXINT)
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yumex/gui/views.py", line 1124, in on_mouse_motion
    tags = widget.get_iter_at_location(x, y).get_tags()
AttributeError: '_ResultTuple' object has no attribute 'get_tags'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yumex/gui/views.py", line 1124, in on_mouse_motion
    tags = widget.get_iter_at_location(x, y).get_tags()
AttributeError: '_ResultTuple' object has no attribute 'get_tags'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yumex/gui/views.py", line 1124, in on_mouse_motion
    tags = widget.get_iter_at_location(x, y).get_tags()
AttributeError: '_ResultTuple' object has no attribute 'get_tags'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/yumex/gui/views.py", line 1124, in on_mouse_motion
    tags = widget.get_iter_at_location(x, y).get_tags()
AttributeError: '_ResultTuple' object has no attribute 'get_tags'
```

**Comment by timlau** [comment]
the result of some API changes in Gtk, I will look into it

**Comment by genodeftest** [comment]
It would be nice to have this fix pushed to Fedora 24 before its final release. I'd even vote for a feature freeze on that. I personally don't care if it's the 4.3.x or the 4.1.x version for F24, but I don't think the 4.3.x version should be on Fedora 22/23.
Rationale: Without this fix, every user will see a "yumex-dnf has crashed" message when running yumex-dnf. This looks pretty bad to users.

**Comment by timlau** [comment]
I was planning to push 4.3.x into F24, before the final release
That why i updated my system to F24, to be able to test it.
There is some issues with the progress bar not counting when doing the install
proberly some changes in DNF, need to be fixed in dnf-daemon
