### ISSUE TITLE
Doesn't work offline

### ISSUE THREAD

**Issue by genodeftest** [timlau/yumex-dnf#95]
Steps to reproduce:
1. be offline (disconnect internet connection)
2. start yumex-dnf

What happens:
Error dialog shows up, closing it will terminate yumex-dnf

What should happen:
Work from cache

Affected version:
yumex-dnf-4.1.6-1.fc24
dnfdaemon-0.3.12-2.fc24
dnf-1.1.7-2.fc24

Additional info:
Possible cause: https://bugzilla.redhat.com/show_bug.cgi?id=1154272

Output:

```
09:40:38: EXCEPTION : g-io-error-quark: GDBus.Error:org.freedesktop.DBus.Python.dnf.exceptions.RepoError: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dnf/repo.py", line 210, in perform
    return super(_Handle, self).perform(result)
  File "/usr/lib64/python3.5/site-packages/librepo/init.py", line 1497, in perform
    _librepo.Handle.perform(self, result)
librepo.LibrepoException: (8, "Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-24&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]", 'An Curl handle error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/dnf/repo.py", line 800, in load
    if self._try_revive():
  File "/usr/lib/python3.5/site-packages/dnf/repo.py", line 714, in _try_revive
    handle.perform()
  File "/usr/lib/python3.5/site-packages/dnf/repo.py", line 214, in perform
    raise _DetailedLibrepoError(exc, source)
dnf.repo._DetailedLibrepoError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/init.py", line 83, in newFunc
    rc = func(*args, **kwargs)
  File "/usr/share/dnfdaemon/dnfdaemon-system", line 207, in SetConfig
    rc = self.set_option(setting, value)
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/init.py", line 694, in set_option
    if hasattr(self.base.conf, option):
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/init.py", line 219, in base
    self._get_base()
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/init.py", line 1070, in _get_base
    self._base.setup_base()
  File "/usr/lib/python3.5/site-packages/dnfdaemon/server/backend.py", line 66, in setup_base
    self.fill_sack()
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 256, in fill_sack
    self._add_repo_to_sack(r.id)
  File "/usr/lib/python3.5/site-packages/dnf/base.py", line 111, in _add_repo_to_sack
    repo.load()
  File "/usr/lib/python3.5/site-packages/dnf/repo.py", line 821, in load
    raise dnf.exceptions.RepoError(msg)
dnf.exceptions.RepoError: Zwischenspeicher f\xfcr Paketquelle \xbbfedora\xab von \xbbhttps://mirrors.fedoraproject.org/metalink?repo=fedora-24&arch=x86_64\xab kann nicht synchronisiert werden: Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-24&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
 (36) 

(yumex-dnf:2729): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by timlau** [comment]
yumex-dnf should handle this better, access to the cache sould not be a problem as dnfdaemon is running as root and is using the root cache.
